spring:
  application:
    name: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 12237
  http2:
    enabled: true
  connection-timeout: 10000
  tomcat:
    protocol: org.apache.coyote.http11.Http11Protocol

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true
